### ISSUE TITLE
Removing 'W A K E U P' feedback.

### ISSUE THREAD

**Issue by andyhqtran** [dominikwilkowski/grunt-wakeup#1]
Either removing this feedback from the console each time it gets run, or add in an option for users to disable/change the message.

`grunt.log.write("\n" + chalk.white.bgGreen.bold('  W A K E  U P  ') + "\n"); //feedback`

**Comment by dominikwilkowski** [comment]
Great idea. Will implement when I get back from holiday. :)

## 

Dominik Wilkowski

M\  +61 432 717 489
W\  DOMINIK-WILKOWSKI.COM
E\   HI@DOMINIK-WILKOWSKI.COM

**Comment by andyhqtran** [comment]
Awesome! It'll be ideal to make the message adjustable, including text styles so that more people can take advantage of that feature. :)

**Comment by dominikwilkowski** [comment]
[Done](https://github.com/dominikwilkowski/grunt-wakeup#optionsoutput) but styling.
Not sure how I would do that. Too many options fur just some color IMO.
Let me know if you have issued :)
